#!/usr/bin/env node
/**
 * Writes assets/manifest.json — the hash and shape of every committed capture.
 *
 * Two jobs. The hashes catch a hand-edit of a generated file, which nothing
 * else would: build-css.mjs --check proves the CSS matches the JSON, but says
 * nothing about whether the JSON still matches Figma. The shape counts give
 * diff.mjs and a human a fast answer to "roughly how far has the kit moved".
 *
 * Usage:
 *   node scripts/manifest.mjs           # rewrite the manifest
 *   node scripts/manifest.mjs --check   # exit 1 if it is stale
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { hashAsset } from './canonical.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ASSETS = join(here, '..', 'assets');
const MANIFEST = join(ASSETS, 'manifest.json');

const TRACKED = [
  'tokens.figma.json',
  'variable-keys.figma.json',
  'components.figma.json',
  'styles.figma.json',
  'pushpin.css',
];

const read = (f) => readFileSync(join(ASSETS, f), 'utf8');
const json = (f) => JSON.parse(read(f));
const hash = (f) => hashAsset(join(ASSETS, f));

const real = (o) => Object.keys(o).filter((k) => !k.startsWith('$'));

const tokens = json('tokens.figma.json');
const keys = json('variable-keys.figma.json');
const components = json('components.figma.json');
const styles = json('styles.figma.json');

const collections = {};
for (const [name, body] of Object.entries(tokens)) {
  if (name.startsWith('$') || name === 'source') continue;
  collections[name] = real(body).length;
}

const manifest = {
  $comment:
    'Hash and shape of every committed capture. Generated by scripts/manifest.mjs; ' +
    'verified by scripts/verify.mjs. Compare against a fresh capture with scripts/diff.mjs.',
  capturedAt: tokens.source.extractedAt,
  figma: {
    fileKey: tokens.source.fileKey,
    fileName: tokens.source.fileName,
    libraryKey: keys.source.libraryKey,
  },
  hashes: Object.fromEntries(TRACKED.map((f) => [f, hash(f)])),
  shape: {
    collections,
    tokensTotal: Object.values(collections).reduce((a, b) => a + b, 0),
    bindable: Object.values(keys.bindable).reduce((n, c) => n + Object.keys(c).length, 0),
    hidden: Object.entries(keys.hiddenFromPublishing)
      .filter(([k]) => !k.startsWith('$'))
      .reduce((n, [, v]) => n + v.length, 0),
    components: Object.keys(components.components).length,
    textStyles: Object.keys(styles.textStyles).length,
    effectStyles: Object.keys(styles.effectStyles).length,
  },
};

const serialised = JSON.stringify(manifest, null, 2) + '\n';

if (process.argv.includes('--check')) {
  let committed;
  try {
    committed = readFileSync(MANIFEST, 'utf8');
  } catch {
    console.error('manifest.json is missing. Run: node scripts/manifest.mjs');
    process.exit(1);
  }
  if (committed !== serialised) {
    console.error('manifest.json is stale. Run: node scripts/manifest.mjs');
    process.exit(1);
  }
  console.log('manifest.json is up to date.');
} else {
  writeFileSync(MANIFEST, serialised);
  const { shape } = manifest;
  console.log(
    `Wrote manifest.json — ${shape.tokensTotal} tokens across ${Object.keys(shape.collections).length} ` +
      `collections, ${shape.bindable} bindable, ${shape.hidden} hidden, ${shape.components} components, ` +
      `${shape.textStyles} text and ${shape.effectStyles} effect styles.`,
  );
}
