#!/usr/bin/env node
/**
 * Writes assets/manifest.json — the hash and shape of every committed capture.
 *
 * Two jobs. The hashes catch a hand-edit of a generated file, which nothing
 * else would: build-css.mjs --check proves the CSS matches the JSON, but says
 * nothing about whether the JSON still matches Figma. The shape counts give
 * diff.mjs and a human a fast answer to "roughly how far has the kit moved".
 *
 * Usage:
 *   node scripts/manifest.mjs           # rewrite the manifest
 *   node scripts/manifest.mjs --check   # exit 1 if it is stale
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { hashAsset } from './canonical.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ASSETS = join(here, '..', 'assets');
const MANIFEST = join(ASSETS, 'manifest.json');

// copy.source.md is here for the same reason the Figma captures are: it is a
// committed verbatim artefact, and the hash is what catches a hand-edit of it.
// copy.source.json is deliberately absent — it is the descriptor rather than
// the capture, and build-copy.mjs already refuses to run when the blob sha it
// records disagrees with the bytes on disk.
// DESIGN.md and design.json are hashed for the same reason pushpin.css is: they
// are generated, committed, and copied verbatim into every project, so the hash
// is what `init` writes into the pin and what tells an existing project it is on
// an older build.
const TRACKED = [
  'tokens.figma.json',
  'variable-keys.figma.json',
  'components.figma.json',
  'component-specs.figma.json',
  'annotations.figma.json',
  'icons.figma.json',
  'styles.figma.json',
  'pushpin.css',
  'DESIGN.md',
  'design.json',
  'copy.source.md',
  'copy.json',
  'copy-map.json',
];

const read = (f) => readFileSync(join(ASSETS, f), 'utf8');
const json = (f) => JSON.parse(read(f));
const hash = (f) => hashAsset(join(ASSETS, f));

const real = (o) => Object.keys(o).filter((k) => !k.startsWith('$'));

const tokens = json('tokens.figma.json');
const keys = json('variable-keys.figma.json');
const components = json('components.figma.json');
const annotations = json('annotations.figma.json');
const icons = json('icons.figma.json');
const styles = json('styles.figma.json');
const specs = json('component-specs.figma.json');
const copy = json('copy.json');

const collections = {};
for (const [name, body] of Object.entries(tokens)) {
  if (name.startsWith('$') || name === 'source') continue;
  collections[name] = real(body).length;
}

const manifest = {
  $comment:
    'Hash and shape of every committed capture. Generated by scripts/manifest.mjs; ' +
    'verified by scripts/verify.mjs. Compare against a fresh capture with scripts/diff.mjs.',
  capturedAt: tokens.source.extractedAt,
  figma: {
    fileKey: tokens.source.fileKey,
    fileName: tokens.source.fileName,
    libraryKey: keys.source.libraryKey,
  },
  // The Annotation Kit is a second Figma source with its own capture date, and
  // it sits beside `figma` rather than inside it because `figma` is read as the
  // Pushpin kit by pull-published.mjs and by freshness.mjs's file-scoped calls.
  annotationKit: {
    fileKey: annotations.source.fileKey,
    fileName: annotations.source.fileName,
    libraryKey: annotations.source.libraryKey,
    capturedAt: annotations.source.extractedAt,
  },
  // The third source, and the surprising one: icons are not published from the
  // Pushpin file at all. They come from the Thumbprint UI Kit by design, one set
  // of glyphs for both systems — and it is a library many accounts cannot reach,
  // so this key is what the generation preflight probes before placing anything.
  iconLibrary: {
    fileKey: icons.source.fileKey,
    fileName: icons.source.fileName,
    libraryKey: icons.source.libraryKey,
    capturedAt: icons.source.extractedAt,
  },
  // The fourth source and the only one that is not Figma. The content design
  // rules are a blob in a GitHub repo, so what pins them is a repo, a ref and a
  // sha rather than a library key — and it is the sha freshness.mjs asks GitHub
  // about, the way it asks Figma about the library keys above.
  copySource: {
    kind: copy.source.kind,
    repo: copy.source.repo,
    path: copy.source.path,
    ref: copy.source.ref,
    sha: copy.source.sha,
    capturedAt: copy.source.extractedAt,
  },
  hashes: Object.fromEntries(TRACKED.map((f) => [f, hash(f)])),
  shape: {
    collections,
    tokensTotal: Object.values(collections).reduce((a, b) => a + b, 0),
    bindable: Object.values(keys.bindable).reduce((n, c) => n + Object.keys(c).length, 0),
    hidden: Object.entries(keys.hiddenFromPublishing)
      .filter(([k]) => !k.startsWith('$'))
      .reduce((n, [, v]) => n + v.length, 0),
    components: Object.keys(components.components).length,
    // Three numbers, because the spec capture is a reduction and one number
    // cannot show it. `componentSpecs` is how much of the catalog has a spec at
    // all, and the other two are the reduction itself — a refresh that halves
    // `specVariants` while holding `specChildren` has dropped coverage, and
    // that is exactly the change a single count would hide.
    componentSpecs: Object.keys(specs.components).length,
    specVariants: specs.source.variantsRecorded,
    specChildren: specs.source.realVariantChildren,
    annotations: Object.keys(annotations.components).length,
    // Two numbers, because an icon is one entry with up to four import keys and
    // the keys are what a run can fail on.
    icons: Object.keys(icons.icons).length,
    iconKeys: icons.source.keyCount,
    textStyles: Object.keys(styles.textStyles).length,
    effectStyles: Object.keys(styles.effectStyles).length,
    copyCodes: Object.keys(copy.codes).length,
    copyTerms: copy.terms.length,
    copyBannedPhrases: copy.bannedPhrases.length,
    // Two numbers again, and for the same reason as the icons: the limits are
    // rows of the upstream's own table, and how many real components they reach
    // is a property of the join in copy-map.json rather than of the rules. Four
    // rows reach nothing on purpose, so the second number moves on its own.
    copyLimits: Object.keys(copy.limits).length,
    copyComponents: Object.keys(copy.components).length,
  },
};

const serialised = JSON.stringify(manifest, null, 2) + '\n';

if (process.argv.includes('--check')) {
  let committed;
  try {
    committed = readFileSync(MANIFEST, 'utf8');
  } catch {
    console.error('manifest.json is missing. Run: node scripts/manifest.mjs');
    process.exit(1);
  }
  if (committed !== serialised) {
    console.error('manifest.json is stale. Run: node scripts/manifest.mjs');
    process.exit(1);
  }
  console.log('manifest.json is up to date.');
} else {
  writeFileSync(MANIFEST, serialised);
  const { shape } = manifest;
  // `bindable` + `hidden` counts Figma variables; `tokensTotal` counts entries
  // in tokens.figma.json, which groups the type ramp's three variables per step
  // into one entry. The two are different quantities and the sentence says so,
  // because 131 + 168 not summing to 273 otherwise reads as an arithmetic bug.
  console.log(
    `Wrote manifest.json — ${shape.tokensTotal} token entries across ` +
      `${Object.keys(shape.collections).length} collections, covering ` +
      `${shape.bindable + shape.hidden} Figma variables (${shape.bindable} bindable, ` +
      `${shape.hidden} hidden from publishing); ${shape.components} components, ` +
      `${shape.componentSpecs} of them with visual specs covering ${shape.specVariants} ` +
      `of ${shape.specChildren} real variants; ${shape.textStyles} text and ` +
      `${shape.effectStyles} effect styles, ` +
      `${shape.annotations} Annotation Kit components, ` +
      `${shape.icons} icons across ${shape.iconKeys} published sizes; and from the ` +
      `content design source, ${shape.copyCodes} severity codes, ${shape.copyTerms} ` +
      `preferred terms and ${shape.copyBannedPhrases} banned phrases, with ` +
      `${shape.copyLimits} length limits reaching ${shape.copyComponents} of those ` +
      `components.`,
  );
}
