/**
 * The two files `init` generates for the impeccable bridge, and how to tell
 * whether either is still the file it wrote.
 *
 * One module because four callers have to agree about it: `init.mjs` records
 * their hashes, `pin.mjs` reports a mismatch at session start, the edit hook
 * reports one on the edit that caused it, and the write guard refuses the edit
 * in the first place. A disagreement between any two of those is worse than
 * any one of them alone.
 *
 * What makes this worth guarding: both files are read as the design system, and
 * `/impeccable document` regenerates them from scratch with an invented visual
 * world. The sidecar's own `schemaVersion` comment says so — a file that does
 * not read as v2 routes impeccable to `document`, and `document` deletes the
 * bridge. Neither file carries anything a human authored, so an overwrite is
 * fully undone by `pushpin init --write --force`.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';

export const DESIGN_REL = 'DESIGN.md';
export const SIDECAR_REL = join('.impeccable', 'design.json');

/** Both generated files, in the order a report should mention them. */
export const GENERATED = [
  { kind: 'design', rel: DESIGN_REL, label: 'DESIGN.md' },
  { kind: 'sidecar', rel: SIDECAR_REL, label: '.impeccable/design.json' },
];

/**
 * The one substring both files carry, deliberately.
 *
 * `DESIGN.md` says `@generated by the pushpin plugin — do not edit.` in its
 * frontmatter; the sidecar says `Generated by the pushpin plugin from its Figma
 * capture` in `$comment`. Testing the raw text for what they share means the
 * guard can judge proposed content without parsing it, which matters because
 * unparseable content must not read as a confident verdict either way.
 */
export const MARKER = 'by the pushpin plugin';

/** Which generated file a path is, or null for anything else. */
export function generatedKind(root, path) {
  const abs = resolve(root, path);
  const rel = relative(resolve(root), abs);
  if (!rel || rel.startsWith('..' + sep) || rel === '..') return null;
  const norm = rel.split(sep).join('/');
  if (norm === DESIGN_REL) return 'design';
  if (norm === SIDECAR_REL.split(sep).join('/')) return 'sidecar';
  return null;
}

/** Whether content still announces itself as ours. */
export const carriesMarker = (text) => typeof text === 'string' && text.includes(MARKER);

/**
 * What a generated file on disk currently is, against what was recorded when it
 * was written. `recorded` is undefined for a project set up before the hashes
 * existed, which is silence rather than a finding — the same distinction
 * `checkHook === undefined` draws for the edit hook.
 *
 * @returns {'absent' | 'unrecorded' | 'current' | 'edited' | 'replaced'}
 */
export function generatedState(root, rel, recorded, hashOf) {
  const abs = join(root, rel);
  if (!existsSync(abs)) return 'absent';
  if (!recorded) return 'unrecorded';
  let body;
  try {
    body = readFileSync(abs, 'utf8');
  } catch {
    return 'unrecorded';
  }
  if (!carriesMarker(body)) return 'replaced';
  let actual;
  try {
    actual = hashOf(abs);
  } catch {
    // Present and still ours, but unreadable in the hashed form — an
    // unparseable sidecar lands here. Not current, and not a clean overwrite.
    return 'edited';
  }
  return actual === recorded ? 'current' : 'edited';
}
